version: '3.8'

services:
  birdclef:
    build:
      context: ./
      args:
        user: ${USER}
    hostname: birdclef
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
            # driver: nvidia
    ports:
      - "7088:8888"
      - "33321:22"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime
      - /etc/passwd:/etc/passwd
      - /etc/shadow:/etc/shadow
      - /etc/group:/etc/group
      - ~/work:/home/${USER}/work
      - ./.jupyter:/home/${USER}/.jupyter
      - ~/.ssh:/home/${USER}/.ssh
    environment:
      USER_NAME: ${USER}
      LD_LIBRARY_PATH: /usr/local/cuda/lib64
    entrypoint: /home/${USER}/work/Kaggle/BirdCLEF/docker/entrypoint.sh
    restart: always
