# change model (b0 -> b1)
title: "v2"
gpu: 0
random_state: 0
n_classes: 5
image_width: 240
image_height: 240
n_channel: 3
train:
  earlystop_patience: 5
  k_fold: 5
  epochs: 60
  batch_size: 32
  val_batch_size: 64
  initial_lr: 0.0001
  transfer_model: /home/kitamura/work/Kaggle/weights/efficientnetb1_notop.h5
  oversample_rate: [10, 5, 5, 1, 5]
  # oversample_rate: [1, 1, 1, 1, 1]
  model:
    is_freeze: False
    is_finetune: True
    class_name: efficientnetb1
    config:
      dropout_rate: 0.7
  optimizer:
    class_name: Adam
    config:
      learning_rate: ${train.initial_lr}
  loss:
    class_name: CategoricalCrossentropy
    config:
      from_logits: True
      label_smoothing: 0.2
